DummyDataStorage | "Homepage Recipe Items" 

"Crispy Buttermilk Fried Chicken"-
<div class="card mt-3"><div class="card-header">Crispy Buttermilk Fried Chicken</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/640803-312x231.jpg" alt="Crispy Buttermilk Fried Chicken"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Crispy-Buttermilk-Fried-Chicken-1" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Lemon and Garlic Slow Roasted Chicken"-
<div class="card mt-3"><div class="card-header">Lemon and Garlic Slow Roasted Chicken</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/649495-312x231.jpg" alt="Lemon and Garlic Slow Roasted Chicken"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Lemon-and-Garlic-Slow-Roasted-Chicken-649495" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Your Basic Low Carb Breakfast"-
<div class="card mt-3"><div class="card-header">Your Basic Low Carb Breakfast</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/1747693-312x231.jpg" alt="Your Basic Low Carb Breakfast"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Your-Basic-Low-Carb-Breakfast-1747693" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Homemade Strawberry Shake"-
<div class="card mt-3"><div class="card-header">Homemade Strawberry Shake</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/715574-312x231.jpg" alt="Homemade Strawberry Shake"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Homemade-Strawberry-Shake-715574" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Mango Black Tea Skinny Cocktai"-
<div class="card mt-3"><div class="card-header">Mango Black Tea Skinny Cocktail</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/650755-312x231.jpg" alt="Mango Black Tea Skinny Cocktail"></img></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Mango-Black-Tea-Skinny-Cocktail-650755" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Ham With Bourbon, Molasses, and Pecan Glaze"-
<div class="card mt-3"><div class="card-header">Ham With Bourbon, Molasses, and Pecan Glaze</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/646216-312x231.jpg" alt="Ham With Bourbon, Molasses, and Pecan Glaze"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Ham-With-Bourbon,-Molasses,-and-Pecan-Glaze-646216" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Lemon Pepper Steak"-
<div class="card mt-3"><div class="card-header">Lemon Pepper Steak</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/649722-312x231.jpg" alt="Lemon Pepper Steak"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Lemon-Pepper-Steak-649722" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Lazy Cobbler"-
<div class="card mt-3"><div class="card-header">Lazy Cobbler</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/649381-312x231.jpg" alt="Lazy Cobbler"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Lazy-Cobbler-649381" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Healthier Southern-Style Green Beans"-
<div class="card mt-3"><div class="card-header">Healthier Southern-Style Green Beans</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/646424-312x231.jpg" alt="Healthier Southern-Style Green Beans"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Healthier-Southern-Style-Green-Beans-646424" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Duck Rumaki"-
<div class="card mt-3"><div class="card-header">Duck Rumaki</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/641717-312x231.jpg" alt="Duck Rumaki"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Duck-Rumaki-641717" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Red Wine Stewed Oxtail"-
<div class="card mt-3"><div class="card-header">Red Wine Stewed Oxtail</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/658126-312x231.jpg" alt="Red Wine Stewed Oxtail"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Red-Wine-Stewed-Oxtail-658126" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Bacon Wrapped Filet Mignon"-
<div class="card mt-3"><div class="card-header">Bacon Wrapped Filet Mignon</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/633338-312x231.jpg" alt="Bacon Wrapped Filet Mignon"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Bacon-Wrapped-Filet-Mignon-633338" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Cranberry Fettuccine Tomato Cream Sauce With Shrimps and Scallops"-
<div class="card mt-3"><div class="card-header">Cranberry Fettuccine Tomato Cream Sauce With Shrimps and Scallops</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/640370-312x231.jpg" alt="Cranberry Fettuccine Tomato Cream Sauce With Shrimps and Scallops"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Cranberry-Fettuccine-Tomato-Cream-Sauce-With-Shrimps-and-Scallops-640370" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Zucchini Chicken Omelette"-
<div class="card mt-3"><div class="card-header">Zucchini Chicken Omelette</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/665734-312x231.jpg" alt="Zucchini Chicken Omelette"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Zucchini-Chicken-Omelette-665734" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>

"Bacon Ice Cream"-
<div class="card mt-3"><div class="card-header">Bacon Ice Cream</div><div class="row g-0"><div class="col-md-4"><img class="card-img-top" src="https://spoonacular.com/recipeImages/633314-312x231.jpg" alt="Bacon Ice Cream"></div><div class="col-md-8"><div class="card-body"><h6 class="card-subtitle text"></h6><p class="card-text"></p><p class="card-text"><strong>Ingredients:</strong> </p><a href="https://spoonacular.com/recipes/Bacon-Ice-Cream-633314" target="_blank" rel="noopener noreferrer" class="btn btn-primary">View on Spoonacular</a></div></div></div></div>